steps:
  # check version
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'node'
    args: [ '--version' ]

  #Build the image
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gamers-meet-293c1/myapp:v1', '.']


  #Push the image
  - id: gcr-push
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gamers-meet-293c1/myapp:v1']

  # Deploy container image to Cloud Run
  - id: cloud-run
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'src'
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      'cloudrunservice',
      '--image',
      'gcr.io/${_PROJECT_ID}/cloudrunservice',
      '--region',
      'managed',
    ]


