steps:
  #Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gamers-meet-293c1/myapp:v1', '.']
    timeout: 180s

  #Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gamers-meet-293c1/myapp:v1']

  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/cloudrunservice"
    args:
      - run
      - --filename= deployment.yaml/
      - --image=gcr.io/gamers-meet-293c1/myapp:v1
      - --cluster=cluster-1