# CloudBuild Pipeline for Staging CloudRun
#-----------------------------------------
steps:
  # Docker Build Image
  - name: 'gcr.io/cloud-builders/docker'
    id  : BUILD
    args: ['build', '-t', '$_SERVICE_IMAGE', '.', '-f', 'app/Dockerfile']



  #Docker push to Artifact service

  - name: 'gcr.io/cloud-builders/docker'
    id  : PUSH
    args: ['push', '$_SERVICE_IMAGE']

  # Docker Deploy image to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    id  : DEPLOY
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --project=$_SERVICE_PROJECT
      - --region=$_SERVICE_REGION
      - --image=$_SERVICE_IMAGE
      - --port=$_PORT

# Display the image in the build results - Build Artifacts
images:
  - $_SERVICE_IMAGE


