steps:
  # check version
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'node'
    args: [ '--version' ]

  #Build the image
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gamers-meet-293c1/myapp:v1', '.']


  #Push the image
  - id: gcr-push
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gamers-meet-293c1/myapp:v1']



