apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: continuous
  namespace: '596714399514'
  selfLink: /apis/serving.knative.dev/v1/namespaces/596714399514/services/continuous
  uid: d78c10da-ca90-4db1-8728-4069cafdb34f
  resourceVersion: AAXelc5j1HA
  generation: 2
  creationTimestamp: '2022-05-09T15:24:22.087410Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: 2f683e40-9e9c-4b0d-80d6-0802049c5bef
    cloud.googleapis.com/location: us-east1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: gamersmeet6813@gmail.com
    serving.knative.dev/lastModifier: gamersmeet6813@gmail.com
    client.knative.dev/user-image: gcr.io/cloudrun/placeholder
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: continuous-placeholder
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 596714399514-compute@developer.gserviceaccount.com
      containers:
        - image: gcr.io/cloudrun/placeholder
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
  traffic:
    - percent: 100
      latestRevision: true
status:
  observedGeneration: 2
  conditions:
    - type: Ready
      status: 'True'
      lastTransitionTime: '2022-05-09T15:24:37.695600Z'
    - type: ConfigurationsReady
      status: 'True'
      lastTransitionTime: '2022-05-09T15:24:37.415899Z'
    - type: RoutesReady
      status: 'True'
      lastTransitionTime: '2022-05-09T15:24:37.695600Z'
  latestReadyRevisionName: continuous-placeholder
  latestCreatedRevisionName: continuous-placeholder
  traffic:
    - revisionName: continuous-placeholder
      percent: 100
      latestRevision: true
  url: https://continuous-fk6hxckzoq-ue.a.run.app
  address:
    url: https://continuous-fk6hxckzoq-ue.a.run.app
