apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudrunservice
  namespace: '596714399514'
  selfLink: /apis/serving.knative.dev/v1/namespaces/596714399514/services/cloudrunservice
  uid: 07fea71d-61c9-41fc-9c54-b85d647a657f
  resourceVersion: AAXei60ilxg
  generation: 1
  creationTimestamp: '2022-05-09T03:17:27.910896Z'
  labels:
    cloud.googleapis.com/location: us-west2
  annotations:
    run.googleapis.com/client-name: gcloud
    serving.knative.dev/creator: 596714399514@cloudbuild.gserviceaccount.com
    serving.knative.dev/lastModifier: 596714399514@cloudbuild.gserviceaccount.com
    client.knative.dev/user-image: us-docker.pkg.dev/cloudrun/container/hello
    run.googleapis.com/client-version: 381.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: cloudrunservice-00001-fer
      annotations:
        run.googleapis.com/client-name: gcloud
        client.knative.dev/user-image: us-docker.pkg.dev/cloudrun/container/hello
        run.googleapis.com/client-version: 381.0.0
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 596714399514-compute@developer.gserviceaccount.com
      containers:
        - image: us-docker.pkg.dev/cloudrun/container/hello
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
  traffic:
    - percent: 100
      latestRevision: true
status:
  observedGeneration: 1
  conditions:
    - type: Ready
      status: 'True'
      lastTransitionTime: '2022-05-09T03:19:30.098968Z'
    - type: ConfigurationsReady
      status: 'True'
      lastTransitionTime: '2022-05-09T03:19:29.519697Z'
    - type: RoutesReady
      status: 'True'
      lastTransitionTime: '2022-05-09T03:19:30.098968Z'
  latestReadyRevisionName: cloudrunservice-00001-fer
  latestCreatedRevisionName: cloudrunservice-00001-fer
  traffic:
    - revisionName: cloudrunservice-00001-fer
      percent: 100
      latestRevision: true
  url: https://cloudrunservice-fk6hxckzoq-wl.a.run.app
  address:
    url: https://cloudrunservice-fk6hxckzoq-wl.a.run.app