export const FST_FETCH_PROFILE = 'FST_FETCH_PROFILE';
export const FST_SET_ERROR = 'FST_SET_ERROR';
export const FST_SET_PROFILE = 'FST_SET_PROFILE';
export const FST_SET_SELECTED_PLATFORM = 'FST_SET_SELECTED_PLATFORM';

